# Generated by Django 5.2.17 on 2026-09-11 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0003_require_employment_grade_location'),
        ('institutions', '0004_seed_reconciled_roles'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='schedule_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='scheduling.scheduleassignment'),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='institutions.institution'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['institution', 'attendance_date'], name='attendance__institu_1d9e20_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['institution', 'status', 'attendance_date'], name='attendance__institu_5c05d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_assignment__isnull', False)), fields=('employee', 'attendance_date', 'schedule_assignment'), name='uniq_attendance_employee_date_schedule'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_assignment__isnull', True)), fields=('employee', 'attendance_date'), name='uniq_attendance_employee_date_unscheduled'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__isnull', True), models.Q(('check_in__isnull', False), ('check_out__gt', models.F('check_in'))), _connector='OR'), name='attendance_checkout_after_checkin'),
        ),
        migrations.AddIndex(
            model_name='attendanceadjustment',
            index=models.Index(fields=['institution', 'status'], name='attendance__institu_140637_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerecord',
            index=models.Index(fields=['institution', 'status'], name='attendance__institu_db4b53_idx'),
        ),
        migrations.AddConstraint(
            model_name='overtimerecord',
            constraint=models.UniqueConstraint(fields=('attendance_record',), name='uniq_overtime_per_attendance'),
        ),
        migrations.AddConstraint(
            model_name='overtimerecord',
            constraint=models.CheckConstraint(condition=models.Q(('approved_minutes__lte', models.F('calculated_minutes'))), name='overtime_approved_not_above_calculated'),
        ),
        migrations.AddConstraint(
            model_name='overtimerecord',
            constraint=models.CheckConstraint(condition=models.Q(('rate_multiplier__gt', 0)), name='overtime_rate_multiplier_positive'),
        ),
    ]
