# Generated by Django 5.2.17 on 2026-09-27 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('documents', '0003_imageasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('MISSED_CLOCK_IN', 'Missed clock-in'), ('MISSED_CLOCK_OUT', 'Missed clock-out'), ('ADD_MISSED_HOURS', 'Add missed hours'), ('TIME_CORRECTION', 'Time correction'), ('NOTE_ONLY', 'Note correction')], default='TIME_CORRECTION', max_length=20),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_adjustments_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='changes_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_adjustments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Changes requested')], default='DRAFT', max_length=10),
        ),
    ]
