# Generated by Django 5.2.17 on 2026-09-11 15:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0003_require_employment_grade_location'),
        ('institutions', '0004_seed_reconciled_roles'),
        ('organization', '0002_location_is_remote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('annual_entitlement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('accrual_method', models.CharField(choices=[('NONE', 'None'), ('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly'), ('DAILY', 'Daily')], default='NONE', max_length=10)),
                ('accrual_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('max_carry_forward', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('min_service_days', models.PositiveIntegerField(default=0)),
                ('max_consecutive_days', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('requires_document', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='institutions.institution')),
            ],
            options={
                'ordering': ('leave_type', '-effective_from', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LeavePolicyDepartmentEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_eligibilities', to='leave.leavepolicy')),
            ],
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='eligible_departments',
            field=models.ManyToManyField(blank=True, related_name='eligible_leave_policies', through='leave.LeavePolicyDepartmentEligibility', to='organization.department'),
        ),
        migrations.CreateModel(
            name='LeavePolicyEmploymentTypeEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('CASUAL', 'Casual')], max_length=12)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_type_eligibilities', to='leave.leavepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicyGenderEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_eligibilities', to='leave.leavepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicyGradeEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.grade')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_eligibilities', to='leave.leavepolicy')),
            ],
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='eligible_grades',
            field=models.ManyToManyField(blank=True, related_name='eligible_leave_policies', through='leave.LeavePolicyGradeEligibility', to='organization.grade'),
        ),
        migrations.CreateModel(
            name='LeavePolicyLocationEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.location')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_eligibilities', to='leave.leavepolicy')),
            ],
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='eligible_locations',
            field=models.ManyToManyField(blank=True, related_name='eligible_leave_policies', through='leave.LeavePolicyLocationEligibility', to='organization.location'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('requested_days', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='documents.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='institutions.institution')),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to='institutions.institution')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaverequest')),
            ],
            options={
                'ordering': ('leave_request', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='institutions.institution')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('accrued', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('adjusted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_balances', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='institutions.institution')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'ordering': ('-year', 'employee', 'leave_type'),
            },
        ),
        migrations.AddConstraint(
            model_name='leavepolicydepartmenteligibility',
            constraint=models.UniqueConstraint(fields=('policy', 'department'), name='uniq_leave_policy_department'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicyemploymenttypeeligibility',
            constraint=models.UniqueConstraint(fields=('policy', 'employment_type'), name='uniq_leave_policy_employment_type'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicygendereligibility',
            constraint=models.UniqueConstraint(fields=('policy', 'gender'), name='uniq_leave_policy_gender'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicygradeeligibility',
            constraint=models.UniqueConstraint(fields=('policy', 'grade'), name='uniq_leave_policy_grade'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicylocationeligibility',
            constraint=models.UniqueConstraint(fields=('policy', 'location'), name='uniq_leave_policy_location'),
        ),
        migrations.AddIndex(
            model_name='leaveapproval',
            index=models.Index(fields=['institution', 'approver', 'status'], name='leave_leave_institu_582264_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveapproval',
            constraint=models.UniqueConstraint(fields=('leave_request', 'sequence'), name='uniq_leave_approval_sequence'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['institution', 'is_active'], name='leave_leave_institu_af7977_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_leave_type_code_per_institution'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['institution', 'status'], name='leave_leave_institu_b369bb_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['institution', 'employee', 'start_date'], name='leave_leave_institu_aeecc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_request_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_days__gt', 0)), name='leave_requested_days_positive'),
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['institution', 'is_active'], name='leave_leave_institu_6b233e_idx'),
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['institution', 'leave_type', 'effective_from'], name='leave_leave_institu_4698cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='leave_policy_effective_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('annual_entitlement__gte', 0)), name='leave_policy_entitlement_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('accrual_rate__gte', 0)), name='leave_policy_accrual_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['institution', 'employee', 'year'], name='leave_leave_institu_6c2bdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='uniq_employee_leave_balance_year'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='leave_opening_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(('accrued__gte', 0)), name='leave_accrued_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(('used__gte', 0)), name='leave_used_nonnegative'),
        ),
    ]
