# Generated by Django 5.2.17 on 2026-09-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_seed_leave_scheduling_attendance'),
        ('leave', '0002_eligibility_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicydepartmenteligibility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='leavepolicyemploymenttypeeligibility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='leavepolicygendereligibility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='leavepolicygradeeligibility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='leavepolicylocationeligibility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='institutions.institution'),
        ),
    ]
