# Generated by Django 5.2.17 on 2026-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leavepolicydepartmenteligibility_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
