# Generated by Django 5.2.17 on 2026-09-27 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0038_hr_admin_without_audit'),
        ('leave', '0005_standard_leave_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapproval',
            name='delegated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_leave_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='changes_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='changes_requested_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('RETURNED', 'Changes requested')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='LeaveRequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_request_comments', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_comments', to='institutions.institution')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leave.leaverequest')),
            ],
            options={
                'ordering': ('leave_request', 'created_at'),
                'indexes': [models.Index(fields=['institution', 'leave_request', 'created_at'], name='leave_leave_institu_b2d339_idx')],
            },
        ),
    ]
