# Generated by Django 5.2.17 on 2026-09-12 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccountsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coa_templates', to='accounting.accountingpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=12)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('is_postable', models.BooleanField(default=True)),
                ('system_mapping_code', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_templates', to='accounting.accounttemplate')),
                ('coa_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_templates', to='accounting.chartofaccountstemplate')),
            ],
            options={
                'ordering': ('coa_template', 'code'),
            },
        ),
        migrations.AddConstraint(
            model_name='chartofaccountstemplate',
            constraint=models.UniqueConstraint(fields=('preset_version', 'name'), name='uniq_coa_template_name_per_version'),
        ),
        migrations.AddConstraint(
            model_name='accounttemplate',
            constraint=models.UniqueConstraint(fields=('coa_template', 'code'), name='uniq_account_template_code'),
        ),
        migrations.AddConstraint(
            model_name='accounttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('system_mapping_code__isnull', False)), fields=('coa_template', 'system_mapping_code'), name='uniq_account_template_mapping_code'),
        ),
    ]
