# Generated by Django 5.2.17 on 2026-09-12 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_chartofaccountstemplate_accounttemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaLocalizationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('version', models.CharField(max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('default_currency', models.CharField(max_length=3)),
                ('tax_authority', models.CharField(max_length=150)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
            ],
            options={
                'ordering': ('-effective_from', 'code'),
                'constraints': [models.UniqueConstraint(fields=('version', 'effective_from'), name='uniq_ghana_localization_version_effective_date'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ghana_localization_dates_valid')],
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('tax_treatment', models.CharField(max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='accounting.accountingpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'code', 'effective_from'),
            },
        ),
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('input_account_mapping_code', models.CharField(blank=True, max_length=100, null=True)),
                ('output_account_mapping_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='accounting.taxcode')),
            ],
            options={
                'ordering': ('tax_code', 'sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='WithholdingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('residency', models.CharField(max_length=30)),
                ('transaction_category', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_vat_withholding_rule', models.BooleanField(default=False)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withholding_rules', to='accounting.accountingpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'code', 'effective_from'),
            },
        ),
        migrations.AddConstraint(
            model_name='taxcode',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code', 'effective_from'), name='uniq_tax_code_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='taxcode',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='tax_code_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='taxcomponent',
            constraint=models.UniqueConstraint(fields=('tax_code', 'code'), name='uniq_tax_component_code_per_tax_code'),
        ),
        migrations.AddConstraint(
            model_name='taxcomponent',
            constraint=models.UniqueConstraint(fields=('tax_code', 'sequence'), name='uniq_tax_component_sequence_per_tax_code'),
        ),
        migrations.AddConstraint(
            model_name='taxcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='tax_component_rate_percent_valid'),
        ),
        migrations.AddConstraint(
            model_name='withholdingrule',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code', 'effective_from'), name='uniq_withholding_rule_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='withholdingrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='withholding_rule_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='withholdingrule',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='withholding_rule_rate_percent_valid'),
        ),
        migrations.AddConstraint(
            model_name='withholdingrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__isnull', True), ('threshold__gte', 0), _connector='OR'), name='withholding_rule_threshold_valid'),
        ),
    ]
