# Generated by Django 5.2.17 on 2026-09-12 13:53

from datetime import date
from decimal import Decimal

from django.db import migrations


EFFECTIVE_FROM = date(2026, 1, 1)
LOCALIZATION_CODE = "GH-LOCALIZATION-2026.1"
GRA_VAT_URL = "https://gra.gov.gh/domestic-tax/tax-types/vat/"
GRA_WHT_URL = "https://gra.gov.gh/portfolio/withholding-tax/"
GRA_VAT_WHT_URL = "https://gra.gov.gh/domestic-tax/tax-types/vat-withholding/"


def _chart_specs(kind):
    specs = [
        ("1000", "Assets", "ASSET", None, "DEBIT", False, "ASSETS_ROOT"),
        ("1100", "Cash and cash equivalents", "ASSET", "1000", "DEBIT", False, "CASH_ROOT"),
        ("1110", "Cash at bank", "ASSET", "1100", "DEBIT", True, "CASH"),
        ("1200", "Trade receivables", "ASSET", "1000", "DEBIT", True, "TRADE_RECEIVABLES"),
        ("1300", "Recoverable tax and levies", "ASSET", "1000", "DEBIT", False, "TAX_INPUT_ROOT"),
        ("1310", "VAT input", "ASSET", "1300", "DEBIT", True, "VAT_INPUT"),
        ("1320", "NHIL input", "ASSET", "1300", "DEBIT", True, "NHIL_INPUT"),
        ("1330", "GETFund input", "ASSET", "1300", "DEBIT", True, "GETFUND_INPUT"),
        ("1340", "VAT withholding credit", "ASSET", "1300", "DEBIT", True, "VAT_WITHHOLDING_CREDIT"),
        ("2000", "Liabilities", "LIABILITY", None, "CREDIT", False, "LIABILITIES_ROOT"),
        ("2100", "Trade payables", "LIABILITY", "2000", "CREDIT", True, "TRADE_PAYABLES"),
        ("2200", "Tax and statutory liabilities", "LIABILITY", "2000", "CREDIT", False, "TAX_PAYABLE_ROOT"),
        ("2210", "VAT output payable", "LIABILITY", "2200", "CREDIT", True, "VAT_OUTPUT_PAYABLE"),
        ("2220", "NHIL payable", "LIABILITY", "2200", "CREDIT", True, "NHIL_PAYABLE"),
        ("2230", "GETFund payable", "LIABILITY", "2200", "CREDIT", True, "GETFUND_PAYABLE"),
        ("2240", "VAT withholding payable", "LIABILITY", "2200", "CREDIT", True, "VAT_WITHHOLDING_PAYABLE"),
        ("2250", "Withholding tax payable", "LIABILITY", "2200", "CREDIT", True, "WITHHOLDING_TAX_PAYABLE"),
        ("2300", "Payroll liabilities", "LIABILITY", "2000", "CREDIT", False, "PAYROLL_LIABILITY_ROOT"),
        ("2310", "PAYE payable", "LIABILITY", "2300", "CREDIT", True, "PAYE_PAYABLE"),
        ("2320", "Tier 1 pension payable", "LIABILITY", "2300", "CREDIT", True, "TIER1_PAYABLE"),
        ("2330", "Tier 2 pension payable", "LIABILITY", "2300", "CREDIT", True, "TIER2_PAYABLE"),
        ("2340", "Payroll payable", "LIABILITY", "2300", "CREDIT", True, "NET_PAY_PAYABLE"),
        ("3000", "Equity and reserves", "EQUITY", None, "CREDIT", False, "EQUITY_ROOT"),
        ("3100", "Retained earnings", "EQUITY", "3000", "CREDIT", True, "RETAINED_EARNINGS"),
        ("4000", "Revenue", "INCOME", None, "CREDIT", False, "REVENUE_ROOT"),
        ("4100", "Sales and service revenue", "INCOME", "4000", "CREDIT", True, "OPERATING_REVENUE"),
        ("5000", "Operating expenses", "EXPENSE", None, "DEBIT", False, "EXPENSE_ROOT"),
        ("5100", "Salaries expense", "EXPENSE", "5000", "DEBIT", True, "SALARIES_EXPENSE"),
        ("5110", "Staff allowance expense", "EXPENSE", "5000", "DEBIT", True, "STAFF_ALLOWANCE_EXPENSE"),
        ("5120", "Employer pension expense", "EXPENSE", "5000", "DEBIT", True, "EMPLOYER_PENSION_EXPENSE"),
        ("5200", "Rent expense", "EXPENSE", "5000", "DEBIT", True, "RENT_EXPENSE"),
    ]
    if kind == "PUBLIC":
        specs += [("3200", "Accumulated fund", "EQUITY", "3000", "CREDIT", True, "ACCUMULATED_FUND"), ("3300", "Restricted funds", "EQUITY", "3000", "CREDIT", True, "RESTRICTED_FUNDS")]
    if kind == "NONPROFIT":
        specs += [("3200", "Unrestricted funds", "EQUITY", "3000", "CREDIT", True, "UNRESTRICTED_FUNDS"), ("3300", "Restricted funds", "EQUITY", "3000", "CREDIT", True, "RESTRICTED_FUNDS"), ("4200", "Grant income", "INCOME", "4000", "CREDIT", True, "GRANT_INCOME")]
    return specs


def _create_preset(apps, code, name, institution_type, framework, status):
    AccountingPreset = apps.get_model("accounting", "AccountingPreset")
    AccountingPresetVersion = apps.get_model("accounting", "AccountingPresetVersion")
    ChartOfAccountsTemplate = apps.get_model("accounting", "ChartOfAccountsTemplate")
    AccountTemplate = apps.get_model("accounting", "AccountTemplate")
    preset, _ = AccountingPreset.objects.get_or_create(code=code, defaults={"country_code": "GH", "name": name, "description": "Versioned Ghana 2026 accounting starter preset.", "institution_type": institution_type, "is_system_managed": True})
    version, _ = AccountingPresetVersion.objects.get_or_create(
        accounting_preset=preset, version_code=f"{code}-2026.1",
        defaults={"localization_version": LOCALIZATION_CODE, "effective_from": EFFECTIVE_FROM, "reporting_framework": framework, "status": status, "source_metadata": {"localization_code": LOCALIZATION_CODE, "default_currency": "GHS", "legal_review_required": institution_type in {"PUBLIC", "NONPROFIT"}, "sources": [{"authority": "GRA", "url": GRA_VAT_URL, "subject": "VAT and levies"}, {"authority": "GRA", "url": GRA_WHT_URL, "subject": "withholding tax"}]}}
    )
    chart, _ = ChartOfAccountsTemplate.objects.get_or_create(preset_version=version, name="Ghana 2026 starter chart", defaults={"description": f"Starter chart for the {institution_type} Ghana preset."})
    templates = {}
    specs = _chart_specs(institution_type)
    for account_code, account_name, account_type, parent_code, normal_balance, is_postable, mapping_code in specs:
        template, _ = AccountTemplate.objects.get_or_create(coa_template=chart, code=account_code, defaults={"name": account_name, "account_type": account_type, "normal_balance": normal_balance, "is_postable": is_postable, "system_mapping_code": mapping_code})
        templates[account_code] = template
    for account_code, _, _, parent_code, _, _, _ in specs:
        if parent_code and templates[account_code].parent_template_id is None:
            templates[account_code].parent_template = templates[parent_code]
            templates[account_code].save(update_fields=("parent_template", "updated_at"))
    return version


def _seed_tax_catalog(apps, preset_version):
    TaxCode = apps.get_model("accounting", "TaxCode")
    TaxComponent = apps.get_model("accounting", "TaxComponent")
    WithholdingRule = apps.get_model("accounting", "WithholdingRule")
    tax_codes = {}
    for code, name, treatment in (("GH-VAT-STD", "Ghana standard VAT and levies", "STANDARD"), ("GH-VAT-ZERO", "Ghana zero-rated supply", "ZERO_RATED"), ("GH-VAT-EXEMPT", "Ghana VAT-exempt supply", "EXEMPT"), ("GH-VAT-RELIEVED", "Ghana VAT-relieved supply", "RELIEVED"), ("GH-VAT-NONTAX", "Non-taxable supply", "NON_TAXABLE"), ("GH-VAT-IMPORT-SERVICE", "Imported service", "IMPORT_SERVICE")):
        tax_codes[code], _ = TaxCode.objects.get_or_create(preset_version=preset_version, code=code, effective_from=EFFECTIVE_FROM, defaults={"name": name, "tax_treatment": treatment, "is_active": True})
    for code, name, rate, input_mapping, output_mapping, sequence in (("VAT", "Value Added Tax", Decimal("15.0000"), "VAT_INPUT", "VAT_OUTPUT_PAYABLE", 1), ("NHIL", "National Health Insurance Levy", Decimal("2.5000"), "NHIL_INPUT", "NHIL_PAYABLE", 2), ("GETFUND", "Ghana Education Trust Fund Levy", Decimal("2.5000"), "GETFUND_INPUT", "GETFUND_PAYABLE", 3)):
        TaxComponent.objects.get_or_create(tax_code=tax_codes["GH-VAT-STD"], code=code, defaults={"name": name, "rate": rate, "input_account_mapping_code": input_mapping, "output_account_mapping_code": output_mapping, "sequence": sequence})
    rules = (("GH-WHT-GOODS-RESIDENT", "Resident supply of goods", "RESIDENT", "GOODS", Decimal("3.0000"), Decimal("2000.00"), False), ("GH-WHT-SERVICES-RESIDENT", "Resident supply of services", "RESIDENT", "SERVICES", Decimal("7.5000"), Decimal("2000.00"), False), ("GH-WHT-WORKS-RESIDENT", "Resident supply of works", "RESIDENT", "WORKS", Decimal("5.0000"), Decimal("2000.00"), False), ("GH-WHT-RENT-RESIDENTIAL", "Residential rent", "RESIDENT", "RENT_RESIDENTIAL", Decimal("8.0000"), None, False), ("GH-WHT-RENT-COMMERCIAL", "Non-residential rent", "RESIDENT", "RENT_COMMERCIAL", Decimal("15.0000"), None, False), ("GH-WHT-DIVIDEND", "Dividend", "ANY", "DIVIDEND", Decimal("8.0000"), None, False), ("GH-VAT-WITHHOLDING-STANDARD", "VAT withholding on standard-rated supply", "ANY", "STANDARD_RATED_SUPPLY", Decimal("7.0000"), None, True))
    for code, name, residency, category, rate, threshold, is_vat in rules:
        WithholdingRule.objects.get_or_create(preset_version=preset_version, code=code, effective_from=EFFECTIVE_FROM, defaults={"name": name, "residency": residency, "transaction_category": category, "rate": rate, "threshold": threshold, "is_vat_withholding_rule": is_vat, "requires_confirmation": True})


def seed_ghana_accounting_2026(apps, schema_editor):
    GhanaLocalizationVersion = apps.get_model("accounting", "GhanaLocalizationVersion")
    GhanaLocalizationVersion.objects.get_or_create(code=LOCALIZATION_CODE, defaults={"version": "2026.1", "effective_from": EFFECTIVE_FROM, "default_currency": "GHS", "tax_authority": "Ghana Revenue Authority", "status": "ACTIVE", "source_metadata": {"sources": [{"authority": "GRA", "url": GRA_VAT_URL, "subject": "VAT, NHIL and GETFund"}, {"authority": "GRA", "url": GRA_WHT_URL, "subject": "withholding tax rates"}, {"authority": "GRA", "url": GRA_VAT_WHT_URL, "subject": "VAT withholding"}], "revalidation_required_on_successor_version": True}})
    versions = (_create_preset(apps, "GH-COMMERCIAL", "Ghana Commercial", "COMMERCIAL", "IFRS", "ACTIVE"), _create_preset(apps, "GH-SME", "Ghana SME", "SME", "IFRS_FOR_SMES", "ACTIVE"), _create_preset(apps, "GH-PUBLIC", "Ghana Public Sector", "PUBLIC", "IPSAS", "DRAFT"), _create_preset(apps, "GH-NONPROFIT", "Ghana Nonprofit", "NONPROFIT", "IFRS", "DRAFT"))
    for preset_version in versions:
        _seed_tax_catalog(apps, preset_version)


def unseed_ghana_accounting_2026(apps, schema_editor):
    apps.get_model("accounting", "AccountingPreset").objects.filter(code__in=("GH-COMMERCIAL", "GH-SME", "GH-PUBLIC", "GH-NONPROFIT")).delete()
    apps.get_model("accounting", "GhanaLocalizationVersion").objects.filter(code=LOCALIZATION_CODE).delete()


class Migration(migrations.Migration):
    dependencies = [("accounting", "0003_ghanalocalizationversion_taxcode_taxcomponent_and_more")]
    operations = [migrations.RunPython(seed_ghana_accounting_2026, unseed_ghana_accounting_2026)]
