# Generated by Django 5.2.17 on 2026-09-12 14:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_seed_ghana_accounting_2026'),
        ('institutions', '0008_seed_accounting_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('vendor_code', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('tax_identification_number', models.CharField(blank=True, max_length=80)),
                ('tax_residency', models.CharField(blank=True, max_length=30)),
                ('taxpayer_type', models.CharField(blank=True, max_length=50)),
                ('vat_registered', models.BooleanField(default=False)),
                ('withholding_category', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='institutions.institution')),
            ],
            options={
                'ordering': ('vendor_code',),
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(max_length=80)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('withholding_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('amount_payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PART_PAID', 'Part paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=12)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='accounting.accountingperiod')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='institutions.institution')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='accounting.journalentry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.vendor')),
            ],
            options={
                'ordering': ('-bill_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='accounting.account')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='accounting.taxcode')),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.vendorbill')),
                ('withholding_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='accounting.withholdingrule')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['institution', 'is_active', 'name'], name='accounting__institu_460240_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('institution', 'vendor_code'), name='uniq_vendor_code_per_institution'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['institution', 'status', 'bill_date'], name='accounting__institu_4d5177_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.UniqueConstraint(fields=('institution', 'vendor', 'bill_number'), name='uniq_vendor_bill_number_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('bill_date'))), name='vendor_bill_due_date_valid'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tax_total__gte', 0), ('withholding_total__gte', 0), ('total_amount__gte', 0), ('amount_payable__gte', 0)), name='vendor_bill_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbillline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('line_total__gte', 0)), name='vendor_bill_line_amounts_valid'),
        ),
    ]
