# Generated by Django 5.2.17 on 2026-09-12 15:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_vendor_vendorbill_vendorbillline_and_more'),
        ('institutions', '0009_seed_accounts_payable_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('customer_code', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('tax_identification_number', models.CharField(blank=True, max_length=80)),
                ('tax_residency', models.CharField(blank=True, max_length=30)),
                ('taxpayer_type', models.CharField(blank=True, max_length=50)),
                ('vat_registered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='institutions.institution')),
            ],
            options={
                'ordering': ('customer_code',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=80)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PART_PAID', 'Part paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=12)),
                ('external_tax_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.accountingperiod')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.customer')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='institutions.institution')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.journalentry')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounting.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounting.taxcode')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('institution', 'customer_code'), name='uniq_customer_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('institution', 'invoice_number'), name='uniq_invoice_number_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('invoice_date'))), name='invoice_due_date_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tax_total__gte', 0), ('total_amount__gte', 0)), name='invoice_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('line_total__gte', 0)), name='invoice_line_amounts_valid'),
        ),
    ]
