# Generated by Django 5.2.17 on 2026-09-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_bankstatementline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='statutory_profile_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='withholding_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='institutionaccountingconfiguration',
            name='is_vat_withholding_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionaccountingconfiguration',
            name='statutory_profile_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='institutionaccountingconfiguration',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='institutionaccountingconfiguration',
            name='vat_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='statutory_profile_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
