# Generated by Django 5.2.17 on 2026-09-12 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_ghana_tax_profiles'),
        ('institutions', '0014_seed_bank_reconciliation_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VATWithholdingCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=100)),
                ('certificate_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VOID', 'Void')], default='DRAFT', max_length=8)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_withholding_certificates', to='institutions.institution')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_withholding_certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_withholding_certificates', to='accounting.vendorbill')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_withholding_certificates_voided', to=settings.AUTH_USER_MODEL)),
                ('withholding_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_withholding_certificates', to='accounting.withholdingrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'certificate_number'), name='uniq_vat_withholding_certificate_number')],
            },
        ),
    ]
