# Generated by Django 5.2.17 on 2026-09-12 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_vat_withholding_certificate'),
        ('institutions', '0015_seed_vat_withholding_certificate_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaComplianceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('authority', models.CharField(default='Ghana Revenue Authority', max_length=150)),
                ('due_date', models.DateField()),
                ('statutory_reference', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], default='OPEN', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ghana_compliance_reminders_completed', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghana_compliance_reminders', to='institutions.institution')),
            ],
            options={
                'ordering': ('due_date', 'code'),
                'constraints': [models.UniqueConstraint(fields=('institution', 'code', 'due_date'), name='uniq_ghana_compliance_reminder')],
            },
        ),
    ]
