# Generated by Django 5.2.17 on 2026-09-27 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_backfill_vendor_bill_approval_trail'),
        ('institutions', '0038_hr_admin_without_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='InvoiceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remind_on', models.DateField()),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone call'), ('LETTER', 'Letter'), ('VISIT', 'Visit')], default='EMAIL', max_length=8)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_reminders', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_reminders', to='institutions.institution')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounting.invoice')),
            ],
            options={
                'ordering': ('remind_on', 'created_at'),
                'indexes': [models.Index(fields=['institution', 'status', 'remind_on'], name='accounting__institu_90a4c6_idx')],
            },
        ),
    ]
