# Generated by Django 5.2.17 on 2026-09-27 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_invoice_collections'),
        ('institutions', '0038_hr_admin_without_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='exception_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BankReconciliationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('statement_opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('statement_closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Reconciled')], default='IN_PROGRESS', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_sessions', to='accounting.bankaccount')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_completed', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliation_sessions', to='institutions.institution')),
                ('last_imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_end', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('bank_account', 'period_start', 'period_end'), name='uniq_reconciliation_session_period'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='reconciliation_session_period_valid')],
            },
        ),
    ]
