# Generated by Django 5.2.17 on 2026-09-27 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_bank_reconciliation_sessions'),
        ('institutions', '0038_hr_admin_without_audit'),
        ('organization', '0004_alter_department_code_alter_grade_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('budget_type', models.CharField(choices=[('OPERATING', 'Operating'), ('CAPITAL', 'Capital'), ('PROJECT', 'Project')], default='OPERATING', max_length=10)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('RETURNED', 'Changes requested'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='organization.department')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='accounting.fiscalyear')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='institutions.institution')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets_owned', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('OPERATING', 'Operating expenses'), ('SUPPLIES', 'Supplies & materials'), ('TRAVEL', 'Travel'), ('CAPITAL', 'Capital equipment'), ('TRANSFERS', 'Transfers'), ('OTHER', 'Other')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('initiative', models.CharField(blank=True, max_length=120)),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.budget')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='institutions.institution')),
            ],
            options={
                'ordering': ('category', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='BudgetNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=4000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_notes', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounting.budget')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_notes', to='institutions.institution')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['institution', 'fiscal_year', 'status'], name='accounting__institu_aeafe8_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_budget_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('allocated__gte', 0)), name='budget_line_allocated_nonnegative'),
        ),
    ]
