# Generated by Django 5.2.17 on 2026-09-27 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_budgets'),
        ('institutions', '0038_hr_admin_without_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('BALANCE_SHEET', 'Statement of financial position'), ('INCOME_STATEMENT', 'Income statement'), ('TRIAL_BALANCE', 'Trial balance'), ('AR_AGING', 'Receivables aging'), ('AP_AGING', 'Payables aging'), ('BUDGET_VS_ACTUAL', 'Budget vs actual')], max_length=20)),
                ('category', models.CharField(choices=[('STANDARD', 'Standard reports'), ('MANAGEMENT', 'Management reports'), ('COMPLIANCE', 'Compliance reports'), ('AUDIT', 'Audit reports'), ('END_OF_PERIOD', 'End of period'), ('CUSTOM', 'Custom reports')], default='CUSTOM', max_length=16)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_standard', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(choices=[('NONE', 'Not scheduled'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='NONE', max_length=10)),
                ('next_run_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='institutions.institution')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_reports_owned', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FinancialReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report_runs', to='institutions.institution')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='accounting.financialreport')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='financialreport',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_financial_report_code'),
        ),
        migrations.AddConstraint(
            model_name='financialreportrun',
            constraint=models.UniqueConstraint(fields=('report', 'version'), name='uniq_financial_report_run_version'),
        ),
    ]
