# Generated by Django 5.2.17 on 2026-09-28 00:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_financial_reports'),
        ('institutions', '0040_search_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(max_length=40)),
                ('operation', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial success'), ('FAILED', 'Failed')], default='QUEUED', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('results', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='institutions.institution')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['institution', 'resource', '-created_at'], name='accounting__institu_0d9dd6_idx')],
            },
        ),
    ]
