# Generated by Django 5.2.17 on 2026-10-05 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_batch_jobs'),
        ('documents', '0003_imageasset'),
        ('employees', '0009_concept_profile_fields'),
        ('institutions', '0042_role_data_scope_read_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('step_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('expense', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('receipt_required_over', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('expense', 'sequence', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='system_mapping_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='finance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='finance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_finance_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('REIMBURSABLE', 'Reimburse the claimant'), ('PETTY_CASH', 'Paid from petty cash')], default='PETTY_CASH', max_length=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='reversal_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_expenses', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_settled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='settlement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_settlements', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='settlement_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_expenses', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='expense',
            name='settlement_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Submitted'), ('RETURNED', 'Returned for changes'), ('FINANCE_REVIEW', 'Finance review'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('system_mapping_code__isnull', False)), fields=('institution', 'system_mapping_code'), name='uniq_account_mapping_per_institution'),
        ),
        migrations.AddField(
            model_name='expenseapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseapproval',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='accounting.expense'),
        ),
        migrations.AddField(
            model_name='expenseapproval',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_approvals', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.expensecategory'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.expense'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_lines', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='receipts',
            field=models.ManyToManyField(blank=True, related_name='expense_lines', to='documents.document'),
        ),
        migrations.AddConstraint(
            model_name='expenseapproval',
            constraint=models.UniqueConstraint(fields=('expense', 'sequence'), name='uniq_expense_approval_sequence'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_expense_category_code'),
        ),
        migrations.AddConstraint(
            model_name='expenseline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_line_amount_positive'),
        ),
    ]
