"use client";

import { useCallback, useState } from "react";

import Alert from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Checkbox, Field, Input, Select, Textarea } from "@/components/ui/Field";
import { Drawer } from "@/components/ui/Overlay";
import { getApiErrorMessage, institutionsApi, isApiRequestError, organizationApi } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
import type { Department, Grade, Location, Position } from "@/types/hr";
import type { OrganizationResourceKind } from "@/components/organization/OrganizationResource";

type Record_ = Department | Position | Grade | Location;

interface Values {
  name: string;
  code: string;
  description: string;
  parent: string;
  department: string;
  level: string;
  address: string;
  city: string;
  country: string;
  timezone: string;
  is_remote: boolean;
  is_active: boolean;
}

const singular: Record<OrganizationResourceKind, string> = { departments: "department", positions: "position", grades: "grade", locations: "location" };

function initialValues(kind: OrganizationResourceKind, record: Record_ | null): Values {
  const values: Values = { name: "", code: "", description: "", parent: "", department: "", level: "", address: "", city: "", country: "", timezone: "", is_remote: false, is_active: true };
  if (!record) return values;
  values.code = record.code;
  values.is_active = record.is_active;
  if (kind === "positions") {
    const position = record as Position;
    return { ...values, name: position.title, department: position.department ?? "", description: position.description };
  }
  if (kind === "departments") {
    const department = record as Department;
    return { ...values, name: department.name, parent: department.parent ?? "", description: department.description };
  }
  if (kind === "grades") {
    const grade = record as Grade;
    return { ...values, name: grade.name, level: grade.level == null ? "" : String(grade.level), description: grade.description };
  }
  const location = record as Location;
  return { ...values, name: location.name, address: location.address, city: location.city, country: location.country, timezone: location.timezone, is_remote: location.is_remote };
}

function payload(kind: OrganizationResourceKind, values: Values): Record<string, unknown> {
  const common = { code: values.code.trim(), is_active: values.is_active };
  if (kind === "positions") return { ...common, title: values.name.trim(), department: values.department || null, description: values.description.trim() };
  if (kind === "departments") return { ...common, name: values.name.trim(), parent: values.parent || null, description: values.description.trim() };
  if (kind === "grades") return { ...common, name: values.name.trim(), level: values.level === "" ? null : Number(values.level), description: values.description.trim() };
  return { ...common, name: values.name.trim(), address: values.address.trim(), city: values.city.trim(), country: values.country, timezone: values.timezone, is_remote: values.is_remote };
}

export function saveOrganizationRecord(kind: OrganizationResourceKind, id: string | null, body: Record<string, unknown>): Promise<Record_> {
  switch (kind) {
    case "departments": return id ? organizationApi.updateDepartment(id, body as Partial<Department>) : organizationApi.createDepartment(body as Partial<Department>);
    case "positions": return id ? organizationApi.updatePosition(id, body as Partial<Position>) : organizationApi.createPosition(body as Partial<Position>);
    case "grades": return id ? organizationApi.updateGrade(id, body as Partial<Grade>) : organizationApi.createGrade(body as Partial<Grade>);
    case "locations": return id ? organizationApi.updateLocation(id, body as Partial<Location>) : organizationApi.createLocation(body as Partial<Location>);
  }
}

/**
 * Add or edit a department, position, grade or location. A blank code is
 * generated by the server (DPT-/POS-/GRD-/LOC-###), so HR only needs a name.
 */
export default function OrganizationForm({ kind, record, open, onClose, onSaved }: { kind: OrganizationResourceKind; record: Record_ | null; open: boolean; onClose: () => void; onSaved: (saved: Record_) => void }) {
  const [values, setValues] = useState<Values>(() => initialValues(kind, record));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const needsDepartments = kind === "departments" || kind === "positions";
  const loadDepartments = useCallback(() => (open && needsDepartments ? organizationApi.listDepartments({ page_size: 100, ordering: "name" }) : Promise.resolve(null)), [open, needsDepartments]);
  const { data: departments } = useApiResource(loadDepartments);
  const loadCatalogues = useCallback(() => (open && kind === "locations" ? institutionsApi.getLocaleCatalogues().catch(() => null) : Promise.resolve(null)), [open, kind]);
  const { data: catalogues } = useApiResource(loadCatalogues);

  const noun = singular[kind];
  const set = <K extends keyof Values>(key: K, value: Values[K]) => setValues((current) => ({ ...current, [key]: value }));
  const fieldError = (name: string) => fieldErrors[name] ?? null;

  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    setSaving(true); setError(null); setFieldErrors({});
    try {
      onSaved(await saveOrganizationRecord(kind, record?.id ?? null, payload(kind, values)));
    } catch (caught) {
      if (isApiRequestError(caught) && caught.fieldErrors) {
        const mapped: Record<string, string> = {};
        for (const [key, messages] of Object.entries(caught.fieldErrors)) mapped[key === "title" ? "name" : key] = Array.isArray(messages) ? String(messages[0]) : String(messages);
        setFieldErrors(mapped);
      }
      setError(getApiErrorMessage(caught));
    } finally {
      setSaving(false);
    }
  };

  // A department cannot sit under itself; other departments are valid parents.
  const departmentOptions = (departments?.results ?? []).filter((item) => item.id !== record?.id && (item.is_active || item.id === values.parent || item.id === values.department));

  return (
    <Drawer
      open={open}
      onClose={() => { if (!saving) onClose(); }}
      title={record ? `Edit ${noun}` : `New ${noun}`}
      description={record ? undefined : "Leave the code blank and ErgonX will generate the next one."}
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={saving}>Cancel</Button>
          <Button type="submit" form="organization-form" loading={saving} loadingLabel="Saving…">{record ? "Save changes" : `Add ${noun}`}</Button>
        </>
      }
    >
      <form id="organization-form" onSubmit={submit} className="space-y-4">
        {error && <Alert tone="danger">{error}</Alert>}
        <Field label={kind === "positions" ? "Position title" : kind === "departments" ? "Department / Functional Area" : "Name"} required error={fieldError("name")}>
          <Input required autoFocus value={values.name} onChange={(event) => set("name", event.target.value)} maxLength={150} placeholder={kind === "departments" ? "e.g. Customer Success" : kind === "positions" ? "e.g. Marketing Officer" : kind === "grades" ? "e.g. Senior Officer" : "e.g. Kumasi Branch"} />
        </Field>
        <Field label="Code" optional helper={record ? undefined : "Generated automatically when left blank."} error={fieldError("code")}>
          <Input value={values.code} onChange={(event) => set("code", event.target.value.toUpperCase())} maxLength={50} className="font-mono" />
        </Field>

        {kind === "departments" && (
          <Field label="Part of" optional helper="Choose a parent to make this a sub-department / functional area. Its head also covers sub-departments / functional areas." error={fieldError("parent")}>
            <Select value={values.parent} onChange={(event) => set("parent", event.target.value)}>
              <option value="">None (top level)</option>
              {departmentOptions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}
            </Select>
          </Field>
        )}
        {kind === "positions" && (
          <Field label="Department / Functional Area" optional error={fieldError("department")}>
            <Select value={values.department} onChange={(event) => set("department", event.target.value)}>
              <option value="">Not assigned</option>
              {departmentOptions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}
            </Select>
          </Field>
        )}
        {kind === "grades" && (
          <Field label="Level" optional helper="Higher numbers are more senior." error={fieldError("level")}>
            <Input type="number" min={0} step={1} value={values.level} onChange={(event) => set("level", event.target.value)} />
          </Field>
        )}
        {kind === "locations" && (
          <>
            <Field label="Address" optional error={fieldError("address")}>
              <Textarea rows={2} value={values.address} onChange={(event) => set("address", event.target.value)} />
            </Field>
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="City" optional error={fieldError("city")}>
                <Input value={values.city} onChange={(event) => set("city", event.target.value)} maxLength={100} />
              </Field>
              <Field label="Country" optional error={fieldError("country")}>
                {catalogues ? (
                  <Select value={values.country} onChange={(event) => set("country", event.target.value)}>
                    <option value="">Not set</option>
                    {catalogues.countries.map((country) => <option key={country.code} value={country.code}>{country.name}</option>)}
                  </Select>
                ) : (
                  <Input value={values.country} onChange={(event) => set("country", event.target.value.toUpperCase().slice(0, 2))} placeholder="GH" maxLength={2} />
                )}
              </Field>
            </div>
            <Field label="Time zone" optional error={fieldError("timezone")}>
              {catalogues ? (
                <Select value={values.timezone} onChange={(event) => set("timezone", event.target.value)}>
                  <option value="">Same as the institution</option>
                  {catalogues.timezones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}
                </Select>
              ) : (
                <Input value={values.timezone} onChange={(event) => set("timezone", event.target.value)} placeholder="Africa/Accra" />
              )}
            </Field>
            <Checkbox checked={values.is_remote} onChange={(event) => set("is_remote", event.target.checked)} label="Remote or hybrid location" description="For people who don't work from a fixed site." />
          </>
        )}
        {kind !== "locations" && (
          <Field label="Description" optional error={fieldError("description")}>
            <Textarea rows={3} value={values.description} onChange={(event) => set("description", event.target.value)} />
          </Field>
        )}
        {record && (
          <Checkbox checked={values.is_active} onChange={(event) => set("is_active", event.target.checked)} label="Active" description={`Inactive ${noun}s stay on existing records but can't be chosen for new ones.`} />
        )}
      </form>
    </Drawer>
  );
}
