# Generated by Django 5.2.17 on 2026-09-11 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=12)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='institutions.institution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'employee_number'),
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern')], max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='employees.employee')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='institutions.institution')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.location')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.position')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='employees.employment')),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['institution', 'status'], name='employees_e_institu_98cffe_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['institution', 'employee_number'], name='employees_e_institu_ced40f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['institution', 'created_at'], name='employees_e_institu_6478eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('institution', 'employee_number'), name='uniq_employee_number_per_institution'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['institution', 'status'], name='employees_e_institu_42bba4_idx'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['institution', 'is_current'], name='employees_e_institu_42e153_idx'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['employee', 'is_current'], name='employees_e_employe_7f82e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee',), name='uniq_current_employment_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('end_date__isnull', True), _connector='OR'), name='current_employment_has_no_end_date'),
        ),
    ]
