# Generated by Django 5.2.17 on 2026-09-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_require_employment_grade_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeoffboarding',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('READY_TO_TERMINATE', 'Ready to terminate'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=24),
        ),
        migrations.AlterField(
            model_name='employeeonboarding',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('READY_FOR_ACTIVATION', 'Ready for activation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=24),
        ),
    ]
