# Generated by Django 5.2.17 on 2026-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employment',
            name='cost_centre',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='employment',
            name='notice_period_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='office_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employment',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='probation_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable'), ('IN_PROGRESS', 'In progress'), ('EXTENDED', 'Extended'), ('COMPLETED', 'Completed')], default='NOT_APPLICABLE', max_length=16),
        ),
        migrations.AddField(
            model_name='employment',
            name='team',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employment',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employment',
            name='work_arrangement',
            field=models.CharField(choices=[('ON_SITE', 'On-site'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], default='ON_SITE', max_length=10),
        ),
        migrations.AddField(
            model_name='employment',
            name='working_pattern',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('SHIFT', 'Shift-based')], default='FULL_TIME', max_length=12),
        ),
    ]
