# Generated by Django 5.2.17 on 2026-09-24 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='method',
            field=models.CharField(choices=[('AUTHENTICATOR_APP', 'Authenticator app'), ('EMAIL_OTP', 'Email one-time code')], default='AUTHENTICATOR_APP', max_length=24),
        ),
        migrations.CreateModel(
            name='EmailOTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_digest', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'expires_at', 'consumed_at'], name='accounts_em_user_id_01e5a2_idx')],
            },
        ),
    ]
