# Generated by Django 5.2.17 on 2026-09-26 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermfa_method_emailotpchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country_code', models.CharField(default='GH', max_length=2)),
                ('organization_size', models.CharField(blank=True, choices=[('1-50', '1–50 employees'), ('51-200', '51–200 employees'), ('201-1000', '201–1,000 employees'), ('1000+', 'More than 1,000 employees')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVITED', 'Invited'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_request', to='accounts.institutionadmininvitation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_in_status_40f047_idx'), models.Index(fields=['email', 'status'], name='accounts_in_email_5d0ade_idx')],
            },
        ),
    ]
