# Generated by Django 5.2.17 on 2026-09-26 18:04

import django.db.models.deletion
from django.db import migrations, models


def link_accepted_invitations(apps, schema_editor):
    # Accepting an invitation creates an institution whose email is the invitee's.
    Invitation = apps.get_model("accounts", "InstitutionAdminInvitation")
    Institution = apps.get_model("institutions", "Institution")
    for invitation in Invitation.objects.filter(status="ACCEPTED", institution__isnull=True):
        institution = Institution.objects.filter(email__iexact=invitation.email).order_by("created_at").first()
        if institution is not None:
            invitation.institution = institution
            invitation.save(update_fields=("institution",))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_institution_access_request'),
        ('institutions', '0037_platform_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionadmininvitation',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_invitations', to='institutions.institution'),
        ),
        migrations.RunPython(link_accepted_invitations, migrations.RunPython.noop),
    ]
