# Generated by Django 5.2.17 on 2026-10-05 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platform_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_key', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CHALLENGED', 'MFA code requested')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['email_key', 'created_at'], name='accounts_au_email_k_f00d81_idx'), models.Index(fields=['ip_address', 'created_at'], name='accounts_au_ip_addr_649af1_idx'), models.Index(fields=['created_at'], name='accounts_au_created_eb75e7_idx')],
            },
        ),
    ]
