# Generated by Django 5.2.17 on 2026-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionaccessrequest',
            name='institution_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institutionaccessrequest',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionaccessrequest',
            name='website_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
