# Generated by Django 5.2.17 on 2026-09-11 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_reference', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('classification', models.CharField(choices=[('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='CONFIDENTIAL', max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('entity_type', models.CharField(blank=True, max_length=150)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='institutions.institution')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['institution', 'is_active'], name='documents_d_institu_32bb3c_idx'), models.Index(fields=['institution', 'category'], name='documents_d_institu_fa560e_idx'), models.Index(fields=['entity_type', 'entity_id'], name='documents_d_entity__bec8fb_idx')],
            },
        ),
    ]
