# Generated by Django 5.2.17 on 2026-09-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stored_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
