# Generated by Django 5.2.17 on 2026-09-24 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_stored_file_alter_document_file_reference'),
        ('institutions', '0034_institution_executive_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('EMPLOYEE', 'Employee'), ('INSTITUTION', 'Institution')], max_length=20)),
                ('owner_id', models.UUIDField()),
                ('stored_file', models.FileField(max_length=500, upload_to='images/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='institutions.institution')),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'owner_type', 'owner_id', 'is_active'], name='documents_i_institu_87952a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('institution', 'owner_type', 'owner_id'), name='uniq_active_image_owner')],
            },
        ),
    ]
