# Generated by Django 5.2.17 on 2026-10-07 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_imageasset'),
        ('employees', '0009_concept_profile_fields'),
        ('institutions', '0043_institution_website_employee_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('document_category', models.CharField(max_length=100)),
                ('employment_types', models.JSONField(blank=True, default=list)),
                ('validity_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='institutions.institution')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirementWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_waivers', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_waivers', to='institutions.institution')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='documents.documentrequirement')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='documentrequirement',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_document_requirement_name'),
        ),
        migrations.AddConstraint(
            model_name='documentrequirementwaiver',
            constraint=models.UniqueConstraint(fields=('requirement', 'employee'), name='uniq_document_waiver_per_employee'),
        ),
    ]
