# Generated by Django 5.2.17 on 2026-10-07 19:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0009_concept_profile_fields'),
        ('institutions', '0043_institution_website_employee_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_competencies', to='institutions.institution')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('self_assessment_due', models.DateField(blank=True, null=True)),
                ('manager_review_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'In progress'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('competencies', models.ManyToManyField(blank=True, related_name='cycles', to='performance.competency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cycles', to='institutions.institution')),
            ],
            options={
                'ordering': ('-period_end', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SELF_ASSESSMENT', 'Self-assessment'), ('MANAGER_REVIEW', 'Manager review'), ('HR_REVIEW', 'HR sign-off'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SELF_ASSESSMENT', max_length=16)),
                ('self_summary', models.TextField(blank=True)),
                ('self_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_summary', models.TextField(blank=True)),
                ('development_plan', models.TextField(blank=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('manager_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='institutions.institution')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews_to_give', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.reviewcycle')),
            ],
            options={
                'ordering': ('employee__last_name', 'employee__first_name'),
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('self_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_comment', models.TextField(blank=True)),
                ('manager_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('manager_comment', models.TextField(blank=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='performance.competency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutions.institution')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance.performancereview')),
            ],
            options={
                'ordering': ('competency__sort_order', 'competency__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_performance_competency_name'),
        ),
        migrations.AddConstraint(
            model_name='reviewcycle',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_review_cycle_name'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['institution', 'status'], name='performance_institu_385d51_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['reviewer', 'status'], name='performance_reviewe_2856c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee'), name='uniq_review_per_cycle_employee'),
        ),
        migrations.AddConstraint(
            model_name='reviewrating',
            constraint=models.UniqueConstraint(fields=('review', 'competency'), name='uniq_rating_per_review_competency'),
        ),
    ]
