# Generated by Django 5.2.17 on 2026-09-11 19:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compensation', '0001_initial'),
        ('documents', '0001_initial'),
        ('employees', '0003_require_employment_grade_location'),
        ('institutions', '0006_seed_compensation_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_system_managed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('country_code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='institutions.institution')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='PayrollPresetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_code', models.CharField(max_length=80)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('payroll_preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='payroll.payrollpreset')),
            ],
            options={
                'ordering': ('payroll_preset', '-effective_from'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionPayrollConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('payroll_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('SEMIMONTHLY', 'Semimonthly'), ('MONTHLY', 'Monthly')], max_length=16)),
                ('payroll_setup_mode', models.CharField(choices=[('PRESET', 'Preset'), ('CUSTOM', 'Custom')], max_length=10)),
                ('pay_day_rule', models.JSONField(blank=True, default=dict)),
                ('rounding_rule', models.JSONField(blank=True, default=dict)),
                ('is_configured', models.BooleanField(default=False)),
                ('configured_at', models.DateTimeField()),
                ('configured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_configurations_completed', to=settings.AUTH_USER_MODEL)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_configuration', to='institutions.institution')),
                ('selected_payroll_preset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institution_configurations', to='payroll.payrollpresetversion')),
            ],
            options={
                'ordering': ('institution',),
            },
        ),
        migrations.CreateModel(
            name='ContributionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('basis', models.CharField(choices=[('BASE_SALARY', 'Base salary'), ('GROSS_PAY', 'Gross pay'), ('TAXABLE_INCOME', 'Taxable income')], max_length=20)),
                ('employee_rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('employer_rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('minimum_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maximum_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_rules', to='payroll.payrollpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'code', 'effective_from'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('authority', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=80)),
                ('calculation_rule', models.JSONField(default=dict)),
                ('offset_days', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_deadlines', to='payroll.payrollpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'code', 'effective_from'),
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employee_contributions', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employer_contributions', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('FINALIZED', 'Finalized'), ('ERROR', 'Error')], default='CALCULATED', max_length=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='institutions.institution')),
            ],
            options={
                'ordering': ('employee__employee_number',),
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_code_snapshot', models.CharField(max_length=80)),
                ('component_name_snapshot', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('COMPENSATION', 'Compensation'), ('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('STATUTORY', 'Statutory'), ('ADJUSTMENT', 'Adjustment'), ('MANUAL', 'Manual')], max_length=16)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pay_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='compensation.paycomponent')),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrecord')),
            ],
            options={
                'ordering': ('payroll_record', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATING', 'Calculating'), ('CALCULATED', 'Calculated'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('statutory_snapshot', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_finalized', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='institutions.institution')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollperiod')),
                ('preset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='payroll.payrollpresetversion')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-payroll_period__start_date', '-run_number'),
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied')], default='DRAFT', max_length=10)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments_decided', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='institutions.institution')),
                ('pay_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='compensation.paycomponent')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payroll.payrollperiod')),
                ('applied_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_adjustments', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField()),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('document_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='documents.document')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='institutions.institution')),
                ('payroll_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='payroll.payrollrecord')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='SpecialIncomeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('income_type', models.CharField(max_length=80)),
                ('eligibility_json', models.JSONField(blank=True, default=dict)),
                ('calculation_json', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('requires_validation', models.BooleanField(default=True)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_income_rules', to='payroll.payrollpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'code', 'effective_from'),
            },
        ),
        migrations.CreateModel(
            name='StatutoryThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit', models.CharField(max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_thresholds', to='payroll.payrollpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'code', 'effective_from'),
            },
        ),
        migrations.CreateModel(
            name='TaxReliefDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('calculation_method', models.CharField(max_length=80)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_count', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('eligibility_json', models.JSONField(blank=True, default=dict)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_definitions', to='payroll.payrollpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'code'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeTaxReliefClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_year', models.PositiveSmallIntegerField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_relief_claims_decided', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_relief_claims', to='employees.employee')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_relief_claims', to='documents.document')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tax_relief_claims', to='institutions.institution')),
                ('relief_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_claims', to='payroll.taxreliefdefinition')),
            ],
            options={
                'ordering': ('-tax_year', 'employee', 'relief_definition'),
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('FLAT', 'Flat'), ('PROGRESSIVE', 'Progressive'), ('SPECIAL', 'Special')], max_length=12)),
                ('residency', models.CharField(default='ANY', max_length=40)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('basis', models.CharField(choices=[('BASE_SALARY', 'Base salary'), ('GROSS_PAY', 'Gross pay'), ('TAXABLE_INCOME', 'Taxable income')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('preset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='payroll.payrollpresetversion')),
            ],
            options={
                'ordering': ('preset_version', 'sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='TaxBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('band_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('tax_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='payroll.taxrule')),
            ],
            options={
                'ordering': ('tax_rule', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='ContributionAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('destination_type', models.CharField(max_length=80)),
                ('destination_reference', models.CharField(max_length=200)),
                ('contribution_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payroll.contributionrule')),
            ],
            options={
                'ordering': ('contribution_rule', 'code'),
                'constraints': [models.UniqueConstraint(fields=('contribution_rule', 'code'), name='uniq_contribution_allocation_code'), models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='contribution_allocation_rate_nonnegative')],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['institution', 'status', 'start_date'], name='payroll_pay_institu_a1b1e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='payroll_period_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('institution', 'start_date', 'end_date'), name='uniq_payroll_period_dates_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='payrollpresetversion',
            constraint=models.UniqueConstraint(fields=('payroll_preset', 'version_code'), name='uniq_payroll_preset_version_code'),
        ),
        migrations.AddConstraint(
            model_name='payrollpresetversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='payroll_preset_version_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='contributionrule',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code', 'effective_from'), name='uniq_contribution_rule_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='contributionrule',
            constraint=models.CheckConstraint(condition=models.Q(('employee_rate__gte', 0)), name='contribution_employee_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='contributionrule',
            constraint=models.CheckConstraint(condition=models.Q(('employer_rate__gte', 0)), name='contribution_employer_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='contributionrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='contribution_rule_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='compliancedeadline',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code', 'effective_from'), name='uniq_compliance_deadline_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='compliancedeadline',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_month__isnull', True), models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 31)), _connector='OR'), name='compliance_deadline_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='compliancedeadline',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='compliance_deadline_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['payroll_record', 'source'], name='payroll_pay_payroll_e3d66e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['component_code_snapshot'], name='payroll_pay_compone_b67cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['institution', 'status', 'started_at'], name='payroll_pay_institu_3d977d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('payroll_period', 'run_number'), name='uniq_payroll_run_number_per_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('institution', 'idempotency_key'), name='uniq_payroll_run_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('run_number__gt', 0)), name='payroll_run_number_positive'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['institution', 'status'], name='payroll_pay_institu_734235_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='uniq_employee_record_per_payroll_run'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['institution', 'status', 'payroll_period'], name='payroll_pay_institu_c952de_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrolladjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='payroll_adjustment_amount_nonzero'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['institution', 'generated_at'], name='payroll_pay_institu_555474_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialincomerule',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code', 'effective_from'), name='uniq_special_income_rule_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='specialincomerule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='special_income_rule_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='statutorythreshold',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code', 'effective_from'), name='uniq_statutory_threshold_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='statutorythreshold',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='statutory_threshold_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='statutorythreshold',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='statutory_threshold_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='taxreliefdefinition',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code'), name='uniq_tax_relief_definition_code'),
        ),
        migrations.AddConstraint(
            model_name='taxreliefdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('default_amount__isnull', True), ('default_amount__gte', 0), _connector='OR'), name='tax_relief_default_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxreliefdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), ('percentage__gte', 0), _connector='OR'), name='tax_relief_percentage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='employeetaxreliefclaim',
            constraint=models.UniqueConstraint(fields=('employee', 'relief_definition', 'tax_year'), name='uniq_employee_tax_relief_claim'),
        ),
        migrations.AddConstraint(
            model_name='employeetaxreliefclaim',
            constraint=models.CheckConstraint(condition=models.Q(('claimed_amount__gte', 0)), name='tax_relief_claim_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='employeetaxreliefclaim',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__gte', 0)), name='tax_relief_approved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='employeetaxreliefclaim',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__lte', models.F('claimed_amount'))), name='tax_relief_approved_not_above_claimed'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.UniqueConstraint(fields=('preset_version', 'code'), name='uniq_tax_rule_code_per_version'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.CheckConstraint(condition=models.Q(('rate__isnull', True), ('rate__gte', 0), _connector='OR'), name='tax_rule_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__isnull', True), ('threshold__gte', 0), _connector='OR'), name='tax_rule_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxband',
            constraint=models.UniqueConstraint(fields=('tax_rule', 'sequence'), name='uniq_tax_band_sequence'),
        ),
        migrations.AddConstraint(
            model_name='taxband',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='tax_band_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxband',
            constraint=models.CheckConstraint(condition=models.Q(('lower_bound__isnull', True), ('lower_bound__gte', 0), _connector='OR'), name='tax_band_lower_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxband',
            constraint=models.CheckConstraint(condition=models.Q(('upper_bound__isnull', True), ('upper_bound__gte', 0), _connector='OR'), name='tax_band_upper_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxband',
            constraint=models.CheckConstraint(condition=models.Q(('band_amount__isnull', True), ('band_amount__gte', 0), _connector='OR'), name='tax_band_amount_nonnegative'),
        ),
    ]
