# Generated by Django 5.2.17 on 2026-09-11 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_require_employment_grade_location'),
        ('institutions', '0007_seed_payroll_access'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_residency', models.CharField(choices=[('RESIDENT', 'Resident'), ('NON_RESIDENT', 'Non-resident')], max_length=16)),
                ('tax_identification_number', models.CharField(blank=True, max_length=80)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_profile', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payroll_profiles', to='institutions.institution')),
            ],
            options={
                'ordering': ('employee__employee_number',),
                'indexes': [models.Index(fields=['institution', 'tax_residency'], name='payroll_emp_institu_f6bbaf_idx')],
            },
        ),
    ]
