# Generated by Django 5.2.17 on 2026-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollrun_accounting_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpayrollconfiguration',
            name='custom_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
