# Generated by Django 5.2.17 on 2026-09-27 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_concept_profile_fields'),
        ('institutions', '0038_hr_admin_without_audit'),
        ('payroll', '0005_custom_payroll_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRunException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('CALCULATION_ERROR', 'Calculation error'), ('NON_POSITIVE_NET_PAY', 'Non-positive net pay'), ('RECONCILIATION_DISCREPANCY', 'Reconciliation discrepancy'), ('LARGE_NET_PAY_CHANGE', 'Large net pay change'), ('NOT_IN_RUN', 'Active employee not in run'), ('MISSING_PAYROLL_PROFILE', 'Payroll profile not configured')], max_length=32)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=8)),
                ('message', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=14)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_exceptions', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_run_exceptions', to='institutions.institution')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='payroll.payrollrun')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('payroll_run', 'status', 'severity', 'created_at'),
                'indexes': [models.Index(fields=['institution', 'payroll_run', 'status'], name='payroll_pay_institu_6aaaea_idx')],
                'constraints': [models.UniqueConstraint(fields=('payroll_run', 'code', 'employee'), name='uniq_payroll_exception_per_run_code_employee')],
            },
        ),
    ]
