# Generated by Django 5.2.17 on 2026-09-11 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_require_employment_grade_location'),
        ('institutions', '0004_seed_reconciled_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibleWorkRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('earliest_start', models.TimeField()),
                ('latest_start', models.TimeField()),
                ('earliest_end', models.TimeField()),
                ('latest_end', models.TimeField()),
                ('required_minutes', models.PositiveIntegerField()),
                ('core_start', models.TimeField(blank=True, null=True)),
                ('core_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_work_rules', to='institutions.institution')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RotationPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_patterns', to='institutions.institution')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='institutions.institution')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('cycle_length_days', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_patterns', to='institutions.institution')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RotationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_steps', to='institutions.institution')),
                ('rotation_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scheduling.rotationpattern')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_steps', to='scheduling.shift')),
                ('shift_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_steps', to='scheduling.shiftpattern')),
            ],
            options={
                'ordering': ('rotation_pattern', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='ShiftPatternDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_index', models.PositiveSmallIntegerField()),
                ('is_off_day', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_pattern_days', to='institutions.institution')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pattern_days', to='scheduling.shift')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='scheduling.shiftpattern')),
            ],
            options={
                'ordering': ('shift_pattern', 'day_index'),
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('schedule_type', models.CharField(choices=[('FIXED', 'Fixed'), ('SHIFT_PATTERN', 'Shift pattern'), ('ROTATING', 'Rotating'), ('FLEXIBLE', 'Flexible')], max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('fixed_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_schedules', to='scheduling.shift')),
                ('flexible_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='scheduling.flexibleworkrule')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='institutions.institution')),
                ('rotation_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='scheduling.rotationpattern')),
                ('shift_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='scheduling.shiftpattern')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='institutions.institution')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.workschedule')),
            ],
            options={
                'ordering': ('-effective_from', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='flexibleworkrule',
            constraint=models.CheckConstraint(condition=models.Q(('required_minutes__gt', 0)), name='flexible_required_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='rotationpattern',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_rotation_pattern_code_per_institution'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['institution', 'is_active'], name='scheduling__institu_258879_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_shift_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_shift_pattern_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_length_days__gt', 0)), name='shift_pattern_cycle_positive'),
        ),
        migrations.AddConstraint(
            model_name='rotationstep',
            constraint=models.UniqueConstraint(fields=('rotation_pattern', 'sequence'), name='uniq_rotation_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='rotationstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shift__isnull', True), ('shift_pattern__isnull', False)), models.Q(('shift__isnull', False), ('shift_pattern__isnull', True)), _connector='OR'), name='rotation_step_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='rotationstep',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='rotation_step_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='shiftpatternday',
            constraint=models.UniqueConstraint(fields=('shift_pattern', 'day_index'), name='uniq_shift_pattern_day_index'),
        ),
        migrations.AddConstraint(
            model_name='shiftpatternday',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_off_day', True), ('shift__isnull', True)), models.Q(('is_off_day', False), ('shift__isnull', False)), _connector='OR'), name='shift_pattern_day_configuration_valid'),
        ),
        migrations.AddIndex(
            model_name='workschedule',
            index=models.Index(fields=['institution', 'is_active'], name='scheduling__institu_60a0fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_work_schedule_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='work_schedule_effective_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_shift__isnull', False), ('flexible_rule__isnull', True), ('rotation_pattern__isnull', True), ('schedule_type', 'FIXED'), ('shift_pattern__isnull', True)), models.Q(('fixed_shift__isnull', True), ('flexible_rule__isnull', True), ('rotation_pattern__isnull', True), ('schedule_type', 'SHIFT_PATTERN'), ('shift_pattern__isnull', False)), models.Q(('fixed_shift__isnull', True), ('flexible_rule__isnull', True), ('rotation_pattern__isnull', False), ('schedule_type', 'ROTATING'), ('shift_pattern__isnull', True)), models.Q(('fixed_shift__isnull', True), ('flexible_rule__isnull', False), ('rotation_pattern__isnull', True), ('schedule_type', 'FLEXIBLE'), ('shift_pattern__isnull', True)), _connector='OR'), name='work_schedule_configuration_valid'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['institution', 'is_current'], name='scheduling__institu_a5b5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['employee', 'effective_from'], name='scheduling__employe_36dc42_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee',), name='uniq_current_schedule_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='scheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='schedule_assignment_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='scheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('effective_to__isnull', True), _connector='OR'), name='current_schedule_has_no_end_date'),
        ),
    ]
