# Generated by Django 5.2.17 on 2026-10-07 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_unify_employee_document_entity_type'),
        ('employees', '0009_concept_profile_fields'),
        ('institutions', '0043_institution_website_employee_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SAFETY', 'Health, safety & environment'), ('TECHNICAL', 'Technical skills'), ('COMPLIANCE', 'Compliance & regulatory'), ('LEADERSHIP', 'Leadership & management'), ('INDUCTION', 'Induction & onboarding'), ('SOFT_SKILLS', 'Professional skills'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('delivery_mode', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('ONLINE', 'Online'), ('ON_THE_JOB', 'On the job'), ('BLENDED', 'Blended')], default='CLASSROOM', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='Internal team or external training provider.', max_length=200)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('certificate_validity_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Shown as mandatory training for the roles it covers.')),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_courses', to='institutions.institution')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('NOT_PASSED', 'Not passed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=12)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('certificate_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='training.trainingcourse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_enrollments', to='employees.employee')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='institutions.institution')),
            ],
            options={
                'ordering': ('-planned_start', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['institution', 'is_active'], name='training_tr_institu_5e539c_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingcourse',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_training_course_code'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['institution', 'status'], name='training_tr_institu_95a00b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['institution', 'certificate_expires_on'], name='training_tr_institu_eac11a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['employee', 'course'], name='training_tr_employe_a7f0cc_idx'),
        ),
    ]
