# Generated by Django 5.2.17 on 2026-09-13 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compensation', '0001_initial'),
        ('employees', '0003_require_employment_grade_location'),
        ('institutions', '0021_seed_operations_access'),
        ('organization', '0002_location_is_remote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('HIRED', 'Hired')], default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='institutions.institution')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('OFFERED', 'Offered'), ('HIRED', 'Hired')], default='DRAFT', max_length=12)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='institutions.institution')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.candidate')),
            ],
            options={
                'ordering': ('-applied_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('interview_type', models.CharField(blank=True, max_length=100)),
                ('location_or_link', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='SCHEDULED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='institutions.institution')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendation', models.CharField(choices=[('STRONG_YES', 'Strong yes'), ('YES', 'Yes'), ('NO', 'No'), ('STRONG_NO', 'Strong no')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='recruitment.application')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_evaluations', to='institutions.institution')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evaluations', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='recruitment.interview')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('CASUAL', 'Casual')], max_length=12)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('opens_on', models.DateField(blank=True, null=True)),
                ('closes_on', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='organization.department')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_job_postings', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='institutions.institution')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='organization.location')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='organization.position')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.jobposting'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('EXTENDED', 'Extended'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn'), ('HIRED', 'Hired')], default='DRAFT', max_length=12)),
                ('proposed_start_date', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('CASUAL', 'Casual')], max_length=12)),
                ('staff_category', models.CharField(choices=[('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('extended_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('terms', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='recruitment.application')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offers', to='organization.department')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offers', to='organization.grade')),
                ('hired_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offer', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='institutions.institution')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offers', to='organization.location')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offers', to='organization.position')),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offers', to='compensation.salarystructure')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_stages', to='institutions.institution')),
            ],
            options={
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='recruitment.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_stage_changes', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_stage_history', to='institutions.institution')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_departures', to='recruitment.recruitmentstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_arrivals', to='recruitment.recruitmentstage')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.recruitmentstage'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['institution', 'status'], name='recruitment_institu_8093ad_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['institution', 'last_name'], name='recruitment_institu_114714_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('institution', 'email'), name='uniq_candidate_email_per_institution'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['institution', 'status', 'scheduled_at'], name='recruitment_institu_e0f117_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['institution', 'application'], name='recruitment_institu_73c140_idx'),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='interview_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='candidateevaluation',
            index=models.Index(fields=['institution', 'application'], name='recruitment_institu_0f8fab_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='candidate_evaluation_score_range'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['institution', 'status'], name='recruitment_institu_fbeb67_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['institution', 'department'], name='recruitment_institu_dc4c07_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_job_posting_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('openings__gt', 0)), name='job_posting_openings_positive'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('closes_on__isnull', True), ('opens_on__isnull', True), ('closes_on__gte', models.F('opens_on')), _connector='OR'), name='job_posting_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['institution', 'status'], name='recruitment_institu_c8c105_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('base_salary__isnull', True), ('base_salary__gte', 0), _connector='OR'), name='offer_salary_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='recruitmentstage',
            index=models.Index(fields=['institution', 'is_active'], name='recruitment_institu_363fa1_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentstage',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_recruitment_stage_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentstage',
            constraint=models.UniqueConstraint(fields=('institution', 'sequence'), name='uniq_recruitment_stage_sequence_per_institution'),
        ),
        migrations.AddIndex(
            model_name='applicationstagehistory',
            index=models.Index(fields=['institution', 'application'], name='recruitment_institu_edb1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['institution', 'status'], name='recruitment_institu_3111c7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['institution', 'job_posting', 'current_stage'], name='recruitment_institu_ab621b_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job_posting', 'candidate'), name='uniq_candidate_application_per_job'),
        ),
    ]
