# Generated by Django 5.2.17 on 2026-09-27 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0038_hr_admin_without_audit'),
        ('organization', '0004_alter_department_code_alter_grade_code_and_more'),
        ('recruitment', '0002_alter_jobposting_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_job_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='organization.grade'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='hiring_reason',
            field=models.CharField(blank=True, choices=[('NEW_ROLE', 'New role'), ('REPLACEMENT', 'Replacement'), ('EXPANSION', 'Team expansion'), ('TEMPORARY_COVER', 'Temporary cover')], max_length=16),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interview_plan',
            field=models.CharField(blank=True, choices=[('SINGLE_PANEL', 'Single panel interview'), ('TWO_STAGE', 'Screening + panel interview'), ('TECHNICAL_PANEL', 'Technical assessment + panel'), ('PRESENTATION_PANEL', 'Presentation + panel')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='qualifications_desirable',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='qualifications_essential',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_job_postings', to='organization.position'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_job_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='target_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16),
        ),
        migrations.CreateModel(
            name='JobPostingTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('HIRING_MANAGER', 'Hiring manager'), ('INTERVIEW_PANEL', 'Interview panel'), ('HR_PARTNER', 'HR business partner'), ('COORDINATOR', 'Recruitment coordinator')], max_length=16)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_team_members', to='institutions.institution')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='recruitment.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('job_posting', 'role', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('job_posting', 'user'), name='uniq_hiring_team_member_per_posting')],
            },
        ),
    ]
