# Generated by Django 5.2.17 on 2026-09-27 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0038_hr_admin_without_audit'),
        ('recruitment', '0003_requisition_plan_approval_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-employed'), ('UNEMPLOYED', 'Not currently employed'), ('STUDENT', 'Student or graduate'), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('SECONDARY', 'Secondary school'), ('DIPLOMA', 'Diploma or certificate'), ('BACHELORS', "Bachelor's degree"), ('MASTERS', "Master's degree"), ('DOCTORATE', 'Doctorate'), ('PROFESSIONAL', 'Professional qualification'), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecruitmentCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_competencies', to='institutions.institution')),
            ],
            options={
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(choices=[('NOT_ASSESSED', 'Not yet assessed'), ('DOES_NOT_MEET', 'Does not meet'), ('PARTIALLY_MEETS', 'Partially meets'), ('MEETS', 'Meets'), ('EXCEEDS', 'Exceeds')], default='NOT_ASSESSED', max_length=16)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='recruitment.application')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competency_ratings', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='institutions.institution')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='recruitment.recruitmentcompetency')),
            ],
            options={
                'ordering': ('competency__sequence',),
            },
        ),
        migrations.AddConstraint(
            model_name='recruitmentcompetency',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_recruitment_competency_name'),
        ),
        migrations.AddIndex(
            model_name='competencyrating',
            index=models.Index(fields=['institution', 'application'], name='recruitment_institu_20c4ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='competencyrating',
            constraint=models.UniqueConstraint(fields=('application', 'competency', 'evaluator'), name='uniq_competency_rating_per_evaluator'),
        ),
    ]
