# Generated by Django 5.2.17 on 2026-09-27 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_department_code_alter_grade_code_and_more'),
        ('recruitment', '0004_candidate_profile_scorecard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='agenda',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_message',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_stage',
            field=models.CharField(blank=True, choices=[('SCREENING', 'Screening call'), ('FIRST_ROUND', 'First round interview'), ('SECOND_ROUND', 'Second round interview'), ('TECHNICAL', 'Technical assessment'), ('FINAL', 'Final interview')], max_length=16),
        ),
        migrations.AddField(
            model_name='interview',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='invitation_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(blank=True, choices=[('VIDEO', 'Video call'), ('PHONE', 'Phone call'), ('IN_PERSON', 'In person'), ('OTHER', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='interview',
            name='panel',
            field=models.ManyToManyField(blank=True, related_name='interview_panels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='offer',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recruitment_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='contract_length_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='letter_body',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='offer',
            name='letter_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offers_reporting', to='organization.position'),
        ),
        migrations.AddField(
            model_name='offer',
            name='response_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='response_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_offer_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_recruitment_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='working_pattern',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('SHIFT', 'Shift-based')], max_length=12),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='SCHEDULED', max_length=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('EXTENDED', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn'), ('HIRED', 'Hired')], default='DRAFT', max_length=16),
        ),
    ]
