# Generated by Django 5.2.17 on 2026-09-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
