# Generated by Django 5.2.17 on 2026-09-26 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_avatar_key'),
        ('organization', '0002_location_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text="Department Head: approves team leave and sees this department's people.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee'),
        ),
    ]
