"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import ErrorState from "@/components/ui/ErrorState";
import LoadingState from "@/components/ui/LoadingState";
import PageHeader from "@/components/ui/PageHeader";
import BackNavigation from "@/components/ui/BackNavigation";
import { getApiErrorMessage, recruitmentApi } from "@/lib/api";
import type { RecruitmentApplication, RecruitmentInterview } from "@/types/recruitment";
import { buttonClasses } from "@/components/ui/Button";

export default function NewEvaluationPage() {
  const router = useRouter(); const [apps, setApps] = useState<RecruitmentApplication[] | null>(null); const [interviews, setInterviews] = useState<RecruitmentInterview[]>([]); const [form, setForm] = useState({ application: "", interview: "", score: "", recommendation: "YES", comments: "" }); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([recruitmentApi.listApplications({ page_size: 100 }), recruitmentApi.listInterviews({ status: "COMPLETED", page_size: 100 })]).then(([applicationRows, interviewRows]) => { setApps(applicationRows.results); setInterviews(interviewRows.results); }).catch((caught) => setError(getApiErrorMessage(caught))); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const score = Number(form.score); if (!form.application || !form.score || score < 0 || score > 100 || saving) { setError("An application and a score between 0 and 100 are required."); return; } setSaving(true); setError(null); try { await recruitmentApi.createCandidateEvaluation({ application: form.application, interview: form.interview || null, score, recommendation: form.recommendation as "STRONG_YES" | "YES" | "NO" | "STRONG_NO", comments: form.comments.trim() }); router.push("/recruitment/evaluations"); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setSaving(false); } };
  if (!apps) return error ? <ErrorState message={error} /> : <LoadingState />; return <div className="space-y-6"><BackNavigation fallback="/recruitment/evaluations" label="Back to Evaluations" /><PageHeader title="Add Evaluation" description="Your interviewer identity is assigned by the backend." /><form onSubmit={submit} className="space-y-5 rounded-2xl border border-line bg-surface p-6"><label className="block"><span className="mb-1.5 block text-sm font-medium">Application</span><select value={form.application} onChange={(event) => setForm((current) => ({ ...current, application: event.target.value, interview: "" }))} className="w-full h-9 rounded-lg border border-line-strong px-3 text-sm"><option value="">Select application</option>{apps.map((app) => <option key={app.id} value={app.id}>Application {app.id.slice(0, 8)}</option>)}</select></label><label className="block"><span className="mb-1.5 block text-sm font-medium">Completed interview</span><select value={form.interview} onChange={(event) => setForm((current) => ({ ...current, interview: event.target.value }))} className="w-full h-9 rounded-lg border border-line-strong px-3 text-sm"><option value="">No linked interview</option>{interviews.filter((item) => !form.application || item.application === form.application).map((item) => <option key={item.id} value={item.id}>{new Date(item.scheduled_at).toLocaleString()}</option>)}</select></label><div className="grid gap-5 md:grid-cols-2"><label><span className="mb-1.5 block text-sm font-medium">Score (0–100)</span><input type="number" min="0" max="100" value={form.score} onChange={(event) => setForm((current) => ({ ...current, score: event.target.value }))} className="w-full h-9 rounded-lg border border-line-strong px-3 text-sm" /></label><label><span className="mb-1.5 block text-sm font-medium">Recommendation</span><select value={form.recommendation} onChange={(event) => setForm((current) => ({ ...current, recommendation: event.target.value }))} className="w-full h-9 rounded-lg border border-line-strong px-3 text-sm">{["STRONG_YES", "YES", "NO", "STRONG_NO"].map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select></label></div><label className="block"><span className="mb-1.5 block text-sm font-medium">Comments</span><textarea rows={5} value={form.comments} onChange={(event) => setForm((current) => ({ ...current, comments: event.target.value }))} className="w-full rounded-lg border border-line-strong px-3 py-2.5 text-sm" /></label>{error && <ErrorState message={error} />}<div className="flex justify-end gap-3"><Link href="/recruitment/evaluations" className="rounded-lg border border-line-strong px-4 py-2.5 text-sm font-medium">Cancel</Link><button disabled={saving} className={buttonClasses({ variant: "primary" })}>{saving ? "Saving…" : "Save Evaluation"}</button></div></form></div>;
}
