# Generated by Django 5.2.17 on 2026-09-28 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0040_search_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('kind', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('REPORT', 'Report')], max_length=10)),
                ('source', models.CharField(max_length=40)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('FINANCE', 'Finance'), ('HR', 'HR'), ('OPERATIONS', 'Operations'), ('RECRUITMENT', 'Recruitment'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=12)),
                ('is_system', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Only me'), ('SHARED', 'Specific people'), ('INSTITUTION', 'Everyone with access')], default='PRIVATE', max_length=12)),
                ('schedule', models.CharField(choices=[('NONE', 'Not scheduled'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=8)),
                ('next_run_on', models.DateField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_items', to='institutions.institution')),
                ('last_refreshed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_items_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AnalyticsShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_shares', to='institutions.institution')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.analyticsitem')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='analyticsitem',
            index=models.Index(fields=['institution', 'status'], name='reports_ana_institu_26a4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsitem',
            index=models.Index(fields=['institution', 'owner'], name='reports_ana_institu_fe7c18_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsitem',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('institution', 'code'), name='uniq_analytics_item_code'),
        ),
        migrations.AddConstraint(
            model_name='analyticsitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('institution', 'kind', 'source'), name='uniq_system_analytics_item'),
        ),
        migrations.AddConstraint(
            model_name='analyticsshare',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='uniq_analytics_share'),
        ),
    ]
