# Generated by Django 5.2.17 on 2026-09-11 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=150)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='institutions.institution')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['institution', 'created_at'], name='audit_audit_institu_c5a7e5_idx'), models.Index(fields=['institution', 'action'], name='audit_audit_institu_437f4f_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
