# Generated by Django 5.2.17 on 2026-09-11 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_institutionfeatureoverride_institutionsetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(max_length=100)),
                ('file_reference', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('READY', 'Ready'), ('COMMITTING', 'Committing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='UPLOADED', max_length=12)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs_initiated', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='institutions.institution')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportRowResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('IMPORTED', 'Imported'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_results', to='operations.importjob')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_row_results', to='institutions.institution')),
            ],
            options={
                'ordering': ('import_job', 'row_number'),
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('result_reference', models.CharField(blank=True, max_length=500)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs_initiated', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='institutions.institution')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['institution', 'status'], name='operations__institu_10f930_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='background_job_progress_lte_100')],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=12)),
                ('result_reference', models.CharField(blank=True, max_length=500)),
                ('error_summary', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs_initiated', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='institutions.institution')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['institution', 'status'], name='operations__institu_7996e7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['institution', 'status'], name='operations__institu_1656f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrowresult',
            constraint=models.UniqueConstraint(fields=('import_job', 'row_number'), name='uniq_row_per_import_job'),
        ),
    ]
