# Generated by Django 5.2.17 on 2026-09-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_seed_reconciled_roles'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='institutions.institution'),
        ),
    ]
