# Generated by Django 5.2.17 on 2026-09-11 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(default='GH', max_length=2)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=64)),
                ('logo', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module_code', models.CharField(default='CORE_HR', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='institutions.institution')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='institutions.permission')),
            ],
            options={
                'ordering': ('institution', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='INVITED', max_length=12)),
                ('is_primary', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='institutions.role')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(choices=[('CORE_HR', 'Core HR'), ('LEAVE', 'Leave'), ('ATTENDANCE', 'Attendance'), ('PAYROLL', 'Payroll'), ('ACCOUNTING', 'Accounting'), ('RECRUITMENT', 'Recruitment'), ('REPORTS', 'Reports')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('configuration_status', models.CharField(choices=[('NOT_CONFIGURED', 'Not configured'), ('IN_PROGRESS', 'In progress'), ('READY', 'Ready'), ('BLOCKED', 'Blocked')], default='NOT_CONFIGURED', max_length=20)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_institution_modules', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='institutions.institution')),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'is_enabled'], name='institution_institu_c58f63_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'module_code'), name='uniq_module_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.CharField(default='ORGANIZATION_SETUP', max_length=100)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('READY', 'Ready')], default='NOT_STARTED', max_length=12)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_institution_onboarding', to=settings.AUTH_USER_MODEL)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='institutions.institution')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('completion_percentage__lte', 100)), name='onboarding_completion_lte_100')],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['institution', 'is_active'], name='institution_institu_73bd9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_role_code_per_institution'),
        ),
        migrations.AddIndex(
            model_name='institutionmembership',
            index=models.Index(fields=['institution', 'status'], name='institution_institu_ad53d8_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionmembership',
            index=models.Index(fields=['user', 'status'], name='institution_user_id_df7371_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.UniqueConstraint(fields=('user', 'institution'), name='uniq_user_institution_membership'),
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'ACTIVE')), fields=('user',), name='uniq_active_primary_membership_per_user'),
        ),
    ]
