# Generated by Django 5.2.17 on 2026-09-11 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_seed_core_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionFeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=150)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('is_sensitive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='SystemFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='country',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='currency',
            new_name='default_currency',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='is_system',
            new_name='is_system_role',
        ),
        migrations.AlterField(
            model_name='role',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='institutions.institution'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('institution__isnull', True)), fields=('code',), name='uniq_global_role_code'),
        ),
        migrations.AddField(
            model_name='institutionfeatureoverride',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionfeatureoverride',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_overrides_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_settings_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionfeatureoverride',
            name='feature_flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_overrides', to='institutions.systemfeatureflag'),
        ),
        migrations.AddConstraint(
            model_name='institutionsetting',
            constraint=models.UniqueConstraint(fields=('institution', 'key'), name='uniq_setting_key_per_institution'),
        ),
        migrations.AddIndex(
            model_name='institutionfeatureoverride',
            index=models.Index(fields=['institution', 'is_enabled'], name='institution_institu_2558d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutionfeatureoverride',
            constraint=models.UniqueConstraint(fields=('institution', 'feature_flag'), name='uniq_feature_override_per_institution'),
        ),
    ]
