# Generated by Django 5.2.17 on 2026-09-12 14:44

from django.db import migrations


PERMISSIONS = {
    "vendor.view": "View vendors",
    "vendor.create": "Create vendors",
    "vendor.update": "Update vendors",
    "vendor_bill.view": "View vendor bills",
    "vendor_bill.create": "Create, edit, and submit vendor bills",
    "vendor_bill.approve": "Approve vendor bills",
    "vendor_bill.post": "Post approved vendor bills",
    "vendor_bill.void": "Void unposted vendor bills",
}

ROLE_PERMISSIONS = {
    "INSTITUTION_ADMIN": tuple(PERMISSIONS),
    "ACCOUNTANT": (
        "vendor.view",
        "vendor.create",
        "vendor.update",
        "vendor_bill.view",
        "vendor_bill.create",
    ),
    "FINANCE_MANAGER": tuple(PERMISSIONS),
    "AUDITOR": ("vendor.view", "vendor_bill.view"),
}


def seed_accounts_payable_access(apps, schema_editor):
    Permission = apps.get_model("institutions", "Permission")
    Role = apps.get_model("institutions", "Role")
    permissions = {}
    for code, name in PERMISSIONS.items():
        permission, _ = Permission.objects.update_or_create(
            code=code, defaults={"name": name, "module_code": "ACCOUNTING"}
        )
        permissions[code] = permission
    for role_code, permission_codes in ROLE_PERMISSIONS.items():
        for role in Role.objects.filter(code=role_code):
            role.permissions.add(*(permissions[code] for code in permission_codes))


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_vendor_vendorbill_vendorbillline_and_more"),
        ("institutions", "0008_seed_accounting_access"),
    ]

    operations = [migrations.RunPython(seed_accounts_payable_access, migrations.RunPython.noop)]
