# Generated by Django 5.2.17 on 2026-09-12 15:15

from django.db import migrations


PERMISSIONS = {
    "customer.view": "View customers", "customer.create": "Create customers", "customer.update": "Update customers",
    "invoice.view": "View invoices", "invoice.create": "Create and edit invoices", "invoice.issue": "Issue invoices", "invoice.void": "Void draft invoices",
}


def seed_accounts_receivable_access(apps, schema_editor):
    Permission = apps.get_model("institutions", "Permission")
    Role = apps.get_model("institutions", "Role")
    permissions = {code: Permission.objects.update_or_create(code=code, defaults={"name": name, "module_code": "ACCOUNTING"})[0] for code, name in PERMISSIONS.items()}
    roles = {
        "INSTITUTION_ADMIN": tuple(PERMISSIONS),
        "ACCOUNTANT": ("customer.view", "customer.create", "customer.update", "invoice.view", "invoice.create"),
        "FINANCE_MANAGER": tuple(PERMISSIONS),
        "AUDITOR": ("customer.view", "invoice.view"),
    }
    for code, granted in roles.items():
        for role in Role.objects.filter(code=code):
            role.permissions.add(*(permissions[item] for item in granted))


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_customer_invoice_invoiceline_and_more"),
        ("institutions", "0009_seed_accounts_payable_access"),
    ]

    operations = [migrations.RunPython(seed_accounts_receivable_access, migrations.RunPython.noop)]
