# Generated by Django 5.2.17 on 2026-09-16 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0022_seed_recruitment_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='classification',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PRIVILEGED', 'Privileged'), ('PLATFORM_ONLY', 'Platform only')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_roles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InstitutionOnboardingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=16)),
                ('required_module', models.CharField(blank=True, max_length=20)),
                ('blocker_code', models.CharField(blank=True, max_length=100)),
                ('blocker_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to='institutions.institution')),
            ],
            options={
                'ordering': ('sequence', 'created_at'),
                'indexes': [models.Index(fields=['institution', 'status'], name='institution_institu_15166f_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='uniq_onboarding_step_per_institution'), models.UniqueConstraint(fields=('institution', 'sequence'), name='uniq_onboarding_step_sequence')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=32)),
                ('current_value', models.PositiveBigIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('reset_policy', models.CharField(choices=[('NEVER', 'Never'), ('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly')], default='NEVER', max_length=10)),
                ('last_reset_key', models.CharField(blank=True, max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_sequences', to='institutions.institution')),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'namespace'], name='institution_institu_4612dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'namespace'), name='uniq_reference_sequence_per_institution_namespace'), models.CheckConstraint(condition=models.Q(('padding__gte', 1), ('padding__lte', 12)), name='reference_sequence_padding_range')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_code', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=150)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_events', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['institution', 'user', 'activity_code'], name='institution_institu_949f23_idx'), models.Index(fields=['institution', 'user', 'occurred_at'], name='institution_institu_d9a5b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preference_key', models.CharField(max_length=100)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'user'], name='institution_institu_c7f3a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'institution', 'preference_key'), name='uniq_user_preference_per_institution')],
            },
        ),
    ]
