# Generated by Django 5.2.17 on 2026-09-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0033_add_audit_view_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='executive_title',
            field=models.CharField(blank=True, default='Executive', max_length=80),
        ),
    ]
