# Generated by Django 5.2.17 on 2026-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0036_staff_self_service_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
