# Generated by Django 5.2.17 on 2026-10-05 11:08

from django.db import migrations, models


def set_system_role_access(apps, schema_editor):
    """Keep behaviour identical: scope and read-only used to be inferred from these codes."""
    Role = apps.get_model("institutions", "Role")
    Role.objects.filter(code="EMPLOYEE").update(data_scope="SELF")
    Role.objects.filter(code="DEPARTMENT_HEAD").update(data_scope="DEPARTMENT")
    Role.objects.filter(code="AUDITOR").update(is_read_only=True)


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0041_hr_admin_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_scope',
            field=models.CharField(choices=[('INSTITUTION', 'Whole institution'), ('DEPARTMENT', 'Own record and departments the member heads'), ('SELF', 'Own records only')], default='INSTITUTION', max_length=12),
        ),
        migrations.AddField(
            model_name='role',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_system_role_access, migrations.RunPython.noop),
    ]
