# Generated by Django 5.2.17 on 2026-10-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0042_role_data_scope_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='employee_size',
            field=models.CharField(blank=True, choices=[('1-50', '1–50 employees'), ('51-200', '51–200 employees'), ('201-1000', '201–1,000 employees'), ('1000+', 'More than 1,000 employees')], max_length=10),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
