# Generated by Django 5.2.17 on 2026-09-11 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_require_employment_grade_location'),
        ('institutions', '0005_seed_leave_scheduling_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_history', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_compensations', to='institutions.institution')),
            ],
            options={
                'ordering': ('-effective_from', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('EMPLOYER_CONTRIBUTION', 'Employer contribution')], max_length=24)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], max_length=12)),
                ('taxable', models.BooleanField(default=False)),
                ('pensionable', models.BooleanField(default=False)),
                ('cash_or_kind', models.CharField(choices=[('CASH', 'Cash'), ('KIND', 'Benefit in kind')], default='CASH', max_length=8)),
                ('recurring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_components', to='institutions.institution')),
            ],
            options={
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='EmployeePayComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_overrides', to='compensation.employeecompensation')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pay_components', to='institutions.institution')),
                ('pay_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_overrides', to='compensation.paycomponent')),
            ],
            options={
                'ordering': ('employee_compensation', 'pay_component', '-effective_from'),
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='institutions.institution')),
            ],
            options={
                'ordering': ('name', 'code'),
            },
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_compensations', to='compensation.salarystructure'),
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('default_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure_components', to='institutions.institution')),
                ('pay_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_components', to='compensation.paycomponent')),
                ('percentage_base_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='percentage_dependent_components', to='compensation.paycomponent')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='compensation.salarystructure')),
            ],
            options={
                'ordering': ('salary_structure', 'sequence', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='paycomponent',
            index=models.Index(fields=['institution', 'component_type', 'is_active'], name='compensatio_institu_2d2963_idx'),
        ),
        migrations.AddIndex(
            model_name='paycomponent',
            index=models.Index(fields=['institution', 'code'], name='compensatio_institu_0d6027_idx'),
        ),
        migrations.AddConstraint(
            model_name='paycomponent',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_pay_component_code_per_institution'),
        ),
        migrations.AddIndex(
            model_name='employeepaycomponent',
            index=models.Index(fields=['institution', 'is_active'], name='compensatio_institu_277b59_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepaycomponent',
            index=models.Index(fields=['employee_compensation', 'pay_component', 'effective_from'], name='compensatio_employe_ee12e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeepaycomponent',
            constraint=models.UniqueConstraint(fields=('employee_compensation', 'pay_component', 'effective_from'), name='uniq_employee_component_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='employeepaycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='employee_component_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='employeepaycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), ('percentage__gte', 0), _connector='OR'), name='employee_component_percentage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='employeepaycomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', False), ('percentage__isnull', True)), models.Q(('amount__isnull', True), ('percentage__isnull', False)), _connector='OR'), name='employee_component_exactly_one_value'),
        ),
        migrations.AddConstraint(
            model_name='employeepaycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='employee_component_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeepaycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('effective_to__isnull', True), _connector='OR'), name='active_employee_component_has_no_end'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['institution', 'is_active'], name='compensatio_institu_38d98b_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_salary_structure_code_per_institution'),
        ),
        migrations.AddIndex(
            model_name='employeecompensation',
            index=models.Index(fields=['institution', 'is_current'], name='compensatio_institu_20375a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensation',
            index=models.Index(fields=['employee', 'effective_from'], name='compensatio_employe_2ed967_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee',), name='uniq_current_compensation_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensation',
            constraint=models.CheckConstraint(condition=models.Q(('base_salary__gte', 0)), name='employee_compensation_salary_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensation',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='employee_compensation_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensation',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('effective_to__isnull', True), _connector='OR'), name='current_compensation_has_no_end_date'),
        ),
        migrations.AddIndex(
            model_name='salarystructurecomponent',
            index=models.Index(fields=['institution', 'salary_structure'], name='compensatio_institu_161ada_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructurecomponent',
            index=models.Index(fields=['salary_structure', 'sequence'], name='compensatio_salary__74ff83_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'pay_component'), name='uniq_component_per_salary_structure'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('default_amount__isnull', True), ('default_amount__gte', 0), _connector='OR'), name='structure_component_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('default_percentage__isnull', True), ('default_percentage__gte', 0), _connector='OR'), name='structure_component_percentage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('default_amount__isnull', True), ('default_percentage__isnull', True), _connector='OR'), name='structure_component_one_default_value'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_base_component__isnull', True), ('default_percentage__isnull', False), _connector='OR'), name='structure_component_base_requires_percentage'),
        ),
    ]
