# Generated by Django 5.2.17 on 2026-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='pay_basis',
            field=models.CharField(choices=[('PAYROLL_PERIOD', 'Configured payroll period')], default='PAYROLL_PERIOD', max_length=32),
        ),
    ]
