# Generated by Django 5.2.17 on 2026-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_employeecompensation_pay_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycomponent',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
