# Generated by Django 5.2.17 on 2026-09-11 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('workflow_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('due_after_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='institutions.role')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow_steps', to='institutions.institution')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.approvalworkflowdefinition')),
            ],
            options={
                'ordering': ('workflow', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=150)),
                ('entity_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='institutions.institution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflows.approvalworkflowdefinition')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_requests', to='workflows.approvalworkflowstep')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RETURN', 'Return'), ('CANCEL', 'Cancel')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to='institutions.institution')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.approvalrequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='workflows.approvalworkflowstep')),
            ],
            options={
                'ordering': ('acted_at',),
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflowdefinition',
            index=models.Index(fields=['institution', 'is_active'], name='workflows_a_institu_754e94_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflowdefinition',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_workflow_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_step_order_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflowstep',
            constraint=models.CheckConstraint(condition=models.Q(('approver_role__isnull', False), ('approver_user__isnull', False), _connector='OR'), name='workflow_step_has_approver'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['institution', 'status'], name='workflows_a_institu_aa2d95_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['entity_type', 'entity_id'], name='workflows_a_entity__a42fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['institution', 'acted_at'], name='workflows_a_institu_bc50cd_idx'),
        ),
    ]
