# Generated by Django 5.2.17 on 2026-10-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def classify_existing(apps, schema_editor):
    """Give existing steps an approver type and leave definitions their trigger."""
    Step = apps.get_model("workflows", "ApprovalWorkflowStep")
    Definition = apps.get_model("workflows", "ApprovalWorkflowDefinition")
    for step in Step.objects.select_related("approver_role"):
        if step.approver_user_id:
            step.approver_type = "USER"
        elif step.approver_role_id and step.approver_role.code == "DEPARTMENT_HEAD":
            # Leave already read a Department Head step as "the requester's own head".
            step.approver_type = "REQUESTER_DEPARTMENT_HEAD"
        else:
            step.approver_type = "ROLE"
        step.save(update_fields=("approver_type",))
    Definition.objects.filter(entity_type__in=("leave.LeaveRequest", "LeaveRequest"), trigger__isnull=True).update(trigger="LEAVE_REQUEST")


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0042_role_data_scope_read_only'),
        ('organization', '0004_alter_department_code_alter_grade_code_and_more'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalworkflowstep',
            name='workflow_step_has_approver',
        ),
        migrations.AddField(
            model_name='approvalworkflowdefinition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflows', to='organization.department'),
        ),
        migrations.AddField(
            model_name='approvalworkflowdefinition',
            name='escalation_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_workflows', to='institutions.role'),
        ),
        migrations.AddField(
            model_name='approvalworkflowdefinition',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflowdefinition',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflowdefinition',
            name='trigger',
            field=models.CharField(blank=True, choices=[('LEAVE_REQUEST', 'Leave request'), ('ATTENDANCE_ADJUSTMENT', 'Attendance adjustment'), ('EXPENSE_CLAIM', 'Expense claim'), ('JOB_REQUISITION', 'Job requisition'), ('OFFER', 'Offer'), ('BUDGET', 'Budget'), ('VENDOR_BILL', 'Vendor bill')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflowstep',
            name='approver_type',
            field=models.CharField(choices=[('USER', 'A named person'), ('ROLE', 'Any member holding a role'), ('REQUESTER_DEPARTMENT_HEAD', "The requester's department head"), ('REQUESTER_MANAGER', "The requester's line manager")], default='ROLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for changes'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='approvalworkflowdefinition',
            name='entity_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='approvalworkflowdefinition',
            name='workflow_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(classify_existing, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='approvalworkflowstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approver_type', 'USER'), ('approver_user__isnull', False)), models.Q(('approver_type', 'ROLE'), ('approver_role__isnull', False)), ('approver_type__in', ('REQUESTER_DEPARTMENT_HEAD', 'REQUESTER_MANAGER')), _connector='OR'), name='workflow_step_approver_matches_type'),
        ),
    ]
